# Generated by Django 4.0.5 on 2022-12-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyClubUser',
            new_name='User',
        ),
    ]
