# Generated by Django 4.0.5 on 2022-12-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_rename_user_userlist_alter_event_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='capacity',
            field=models.CharField(blank=True, max_length=15, verbose_name='Capacity'),
        ),
    ]
