# Generated by Django 4.0.5 on 2022-12-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_venue_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.CharField(max_length=15, verbose_name='Capacity'),
        ),
    ]
